apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    dnsPolicy: ClusterFirst
    spec:
      containers:
      - image: 'rannybal2024/identity-service:IMAGE_TAG'
        name: identity-service
        ports:
        - containerPort: 9096
          name: http
          protocol: TCP
        env:
          - name: _JAVA_OPTIONS
            value: "-Xmx512m -Xms50m -Deureka.instance.leaseRenewalIntervalInSeconds=30"
          - name: POSTGRES_HOST
            value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
          - name: POSTGRES_PORT
            value: "25061"
          - name: POSTGRES_DB
            value: "identitydb"
          - name: POSTGRES_USER
            value: "doadmin"
          - name: POSTGRES_PARAMS
            value: "&ssl=true&sslmode=require"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_DOADMIN_PASSWORD
          - name: BINARY_CONTENT_DB_HOST
            value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
          - name: BINARY_CONTENT_DB_PORT
            value: "25061"
          - name: BINARY_CONTENT_DB_NAME
            value: "binarycontentdb"
          - name: BINARY_CONTENT_DB_USERNAME
            value: "doadmin"
          - name: BINARY_CONTENT_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PG_DOADMIN_PASSWORD
          - name: BINARY_CONTENT_DB_PARAMS
            value: "ssl=true&sslmode=require"
          - name: BINARY_CONTENT_URL
            value: "http://not-yet-in-use/"
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "my-cluster-kafka-bootstrap:9092"
          - name: KAFKA_JAAS_CONFIG
            value: ""
          - name: MAIL_DEBUG
            value: "true"
          - name: SMTP_HOST
            value: "maildev"
          - name: SMTP_PORT
            value: "25"
          - name: SMTP_DEFAULT_FROM
            value: "support@kolanot.co.uk"
          - name: SMTP_USERNAME
            value: ""
          - name: SMTP_PASSWORD
            value: ""
          - name: SMTP_AUTH
            value: "false"
          - name: SMTP_STARTTLS
            value: "false"
          - name: KEYCLOAK_URL
            value: "http://keycloak:8080/auth"
          - name: KEYCLOAK_REALM
            value: "master"
          - name: KEYCLOAK_ADMIN_USERNAME
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KEYCLOAK_ADMIN_CLIENT_ID
            value: "admin-cli"
          - name: KEYCLOAK_ADMIN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KEYCLOAK_ADMIN_CLIENT_SECRET
          - name: CATALOG_SERVICE_OAUTH_CLIENT_ID
            value: "catalog-service-client"
          - name: CATALOG_SERVICE_OAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: CATALOG_SERVICE_OAUTH_SECRET
          - name: BP_SERVICE_OAUTH_CLIENT_ID
            value: "bp-service-client"
          - name: BP_SERVICE_OAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: BP_SERVICE_OAUTH_SECRET
          - name: OAUTH_CLIENT_ID
            value: "nimble_client"
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: OAUTH_CLIENT_SECRET
          - name: OAUTH_CLIENT_ACCESSTOKEN_URI
            value: "http://keycloak:8080/auth/realms/master/protocol/openid-connect/token"
          - name: SUPPORT_EMAIL
            value: "support@kolayam.co.uk"
          - name: COMPATA_DATA_UPDATE_EMAIL
            value: "support@kolayam.co.uk"
          - name: ROCKET_CHAT
            value: "false"
          - name: CHAT_SERVICE_URL
            value: "http://rocketchat-service:3000"
          - name: ROCKET_CHAT_USER
            value: "support@kolanot.co.uk"
          - name: ROCKET_CHAT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: ROCKET_CHAT_PASSWORD
          - name: INDEXING_SERVICE_URL
            value: "http://indexing-service:8080/"
          - name: KEYCLOAK_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: KEYCLOAK_PUBLIC_KEY_1
          - name: FEDERATION_INSTANCE_ID
            value: "kerberos"
          - name: DISCOVERY_ENABLED
            value: "true"
          - name: CONFIG_SERVER_URI
            value: "http://config-server:8888"
          - name: CONFIG_SERVER_FAILFAST
            value: "true"
          - name: DISCOVERY_SERVER_URI
            value: "http://service-discovery:8761"
          - name: DISCOVERY_PREFER_IP
            value: "false"
          - name: FRONTEND_URL
            value: "https://www.kolayam.co.uk"
          - name: CATALOGUE_SERVICE_URL
            value: "http://catalog-service-srdc:8095"
          - name: BUSINESS_PROCESS_SERVICE_URL
            value: "http://business-process-service:8081"
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: STRIPE_SECRET_KEY
          - name: STRIPE_REFRESH_URL
            value: "https://www.kolayam.co.uk/#/user-mgmt/company-settings"
          - name: STRIPE_RETURN_URL
            value: "https://www.kolayam.co.uk/#/user-mgmt/company-settings"
          - name: DELEGATE_SERVICE_URL
            value: "http://delegate-service:8080"
          - name: PLATFORM_NAME
            value: "DEVELOPMENT"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
