apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - image: 'rannybal2024/identity-service:IMAGE_TAG'
        name: identity-service
        ports:
        - containerPort: 9096
          name: http
          protocol: TCP
        env:
          - name: _JAVA_OPTIONS
            value: "-Xmx128m -Xms50m -Deureka.instance.leaseRenewalIntervalInSeconds=30"
          - name: POSTGRES_HOST
            value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
          - name: POSTGRES_PORT
            value: "25060"
          - name: POSTGRES_DB
            value: "identitydb"
          - name: POSTGRES_USER
            value: "doadmin"
          - name: POSTGRES_PARAMS
            value: "&ssl=true&sslmode=require"
          - name: POSTGRES_PASSWORD
            value: "AVNS_xN6h3TZAvlOwe4vdAdk"
          - name: BINARY_CONTENT_DB_HOST
            value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
          - name: BINARY_CONTENT_DB_PORT
            value: "25060"
          - name: BINARY_CONTENT_DB_NAME
            value: "binarycontentdb"
          - name: BINARY_CONTENT_DB_USERNAME
            value: "doadmin"
          - name: BINARY_CONTENT_DB_PASSWORD
            value: "AVNS_xN6h3TZAvlOwe4vdAdk"
          - name: BINARY_CONTENT_DB_PARAMS
            value: "&ssl=true&sslmode=require"
          - name: BINARY_CONTENT_URL
            value: "http://not-yet-in-use/"
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "my-cluster-kafka-bootstrap:9092"
          - name: KAFKA_JAAS_CONFIG
            value: ""
          - name: SMTP_HOST
            value: "smtp.gmail.com"
          - name: SMTP_PORT
            value: "587"
          - name: SMTP_DEFAULT_FROM
            value: "support@kolanot.co.uk"
          - name: SMTP_USERNAME
            value: "support@kolanot.co.uk"
          - name: SMTP_PASSWORD
            value: "lzuqcjludynkrtvd"
          - name: SMTP_AUTH
            value: "true"
          - name: SMTP_STARTTLS
            value: "true"
          - name: KEYCLOAK_URL
            value: "http://keycloak:8080/auth"
          - name: KEYCLOAK_REALM
            value: "master"
          - name: KEYCLOAK_ADMIN_USERNAME
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "123456"
          - name: KEYCLOAK_ADMIN_CLIENT_ID
            value: "admin-cli"
          - name: KEYCLOAK_ADMIN_CLIENT_SECRET
            value: "18f8ba5e-4602-4776-8b50-f8e5116c48f7"
          - name: CATALOG_SERVICE_OAUTH_CLIENT_ID
            value: "catalog-service-client"
          - name: CATALOG_SERVICE_OAUTH_SECRET
            value: "09eae741-0684-4798-b728-aa6a8e59ca71"
          - name: BP_SERVICE_OAUTH_CLIENT_ID
            value: "bp-service-client"
          - name: BP_SERVICE_OAUTH_SECRET
            value: "621c1ec2-6753-4ead-925f-a5df24876a2b"
          - name: OAUTH_CLIENT_ID
            value: "nimble_client"
          - name: OAUTH_CLIENT_SECRET
            value: "710ac188-637b-4373-a237-d83765d07893"
          - name: OAUTH_CLIENT_ACCESSTOKEN_URI
            value: "http://keycloak:8080/auth/realms/master/protocol/openid-connect/token"
          - name: ROCKET_CHAT
            value: "false"
          - name: INDEXING_SERVICE_URL
            value: "http://indexing-service:8080/"
          - name: KEYCLOAK_PUBLIC_KEY
            value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjbTzPIh+ff5lTVW0c4veuS3Ers+29+h9mXXcwkojaDRwzHmf1ZCVvJY3eNy6NCu0SwVksA2tusBZK+qiSo4Kk24DDTNz1JQ7HDvXzTxH6Vfz8vPC9qq+kOPBqUOXctlNTiyz+8uEA6rS1ZpzcbVOdds0xx9k0pSlZhXxbeJlq+m8nS5cWNiAMnS4Z0UQDJXNL5Y8a4z8XTPlX5cv9B2cikQpQ97grnUQ1ihAs+7gw6Jo1DyU+6V1KEYK89yPtn8bSvsgVSIx0g97kBS7c2EhmqBgQ5h5zXW7nLXTiNE+va7Gk0Bfaf6jw5j8p5/uigrRlmgoTQxvgE7oiviJA18ZTQIDAQAB"
          - name: FEDERATION_INSTANCE_ID
            value: "kerberos"
          - name: DISCOVERY_ENABLED
            value: "true"
          - name: CONFIG_SERVER_URI
            value: "http://config-server:8888"
          - name: CONFIG_SERVER_FAILFAST
            value: "true"
          - name: DISCOVERY_SERVER_URI
            value: "http://service-discovery:8761"
          - name: DISCOVERY_PREFER_IP
            value: "false"
          - name: FRONTEND_URL
            value: "https://nimble.kolayam.co.uk"
          - name: CATALOGUE_SERVICE_URL
            value: "http://catalog-service-srdc:8095"
          - name: BUSINESS_PROCESS_SERVICE_URL
            value: "http://business-process-service:8081"
          - name: STRIPE_SECRET_KEY
            value: "sk_test_51NYrpWDm3eNdEyUnTxNx27CcIFD22jjnT3zqtt8MAQGzsP1oe6rGqdhQgsaZKR7EtOSPznIEw80rBE0G65jLEQ8I006Oy5RGOc"
          - name: STRIPE_REFRESH_URL
            value: "https://www.kolayam.co.uk/#/user-mgmt/company-settings"
          - name: STRIPE_RETURN_URL
            value: "https://www.kolayam.co.uk/#/user-mgmt/company-settings"

---

kind: Service
metadata:
  name: identity-service
  labels:
    app: nimble-platform
    name: identity-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9096
      targetPort: 9096
  selector:
    app: nimble-platform
    name: identity-service